### ISSUE TITLE
[Feature Request]: Allow DeepGNN Server to start without features using the same meta.json

### ISSUE THREAD

**Issue by Tomcli** [microsoft/DeepGNN#296]
Our team is leveraging DeepGNN to query both compute graph and node/edge features for training our GNN models due to its extensive feature set and robust performance across various environments. DeepGNN loads all compute graph information along with node/edge features based on the configuration specified in the `meta.json` file. However, some of our environments require a different method to host node/edge features due to performance and network limitations.

Currently, the only way to configure what DeepGNN loads is through the `meta.json` file. We prefer to keep this file unchanged because it is generated by DeepGNN and shared across multiple environments. To address this, we propose adding a flag to the DeepGNN Server that allows us to opt out of loading node/edge features without modifying the `meta.json.` This approach will enable us to conduct A/B testing and canary deployments more efficiently.

**Comment by coledie** [comment]
We can achive the results if you are willing to have 2 meta files. Generating the second meta.json is as simple as loading the original as a dictionary, then editing the specific values, and saving it. Then we can just do a python side change to allow overriding metapath - maybe 5 line changes? Code here, https://github.com/microsoft/DeepGNN/blob/549beee206600ada35184fc213e1d33e1be763b9/src/python/deepgnn/graph_engine/snark/distributed.py#L78
Does this work for you?

We could add a parameter override for the feature counts the way you described, but these values would have to get piped through several layers of abstraction down to the meta reader in C++ https://github.com/microsoft/DeepGNN/blob/549beee206600ada35184fc213e1d33e1be763b9/src/cc/lib/graph/metadata.cc#L65

In my opinion the first suggestion is much better since it will generalize to different scenarios saving dev work down the line and it keeps the code clean, but if you can allocate the devs you can do it however you'd like.

**Comment by coledie** [comment]
@Tomcli

**Comment by coledie** [comment]
I saw the PR, if you want to stay with that solution I'll review it today and we can merge.

**Comment by MortezaRamezani** [comment]
I think @coledie is the better choice. TBF this use-case is unique (where the same dataset can be used with and without feature in DeepGNN), so a `--config-path` flag and default value being `meta.json` would be the way to go IMO.

**Comment by coledie** [comment]
FYI @Tomcli

**Comment by Tomcli** [comment]
@coledie There are several places that are hard coded with the `meta.json` path. If we only change the python code, the c++ code in the metadata.cc module will still look for `data_path/meta.json` because it doesn't have a meta_path parameter. I feel like it will be same amount of work to support a new meta_path and we need to maintain 2 different meta_path files.
https://github.com/microsoft/DeepGNN/blob/549beee206600ada35184fc213e1d33e1be763b9/src/cc/lib/graph/metadata.cc#L48
